### ISSUE TITLE
Unable to sync previous matches 

### ISSUE THREAD

**Issue by MoShU23** [majikat768/HuntStatsLogger#2]
Version: v0.2.0  

I'm having trouble trying to sync my previous matches, all the .json files are there but when I sync, nothing happens. All the previous games are displayed in the program and any new game I have is syncing just fine. The log looks like this: https://pastebin.com/k87fsSL9

I also tried v0.1.0, and when I sync, I get this: https://pastebin.com/mNELtgSM , all the .json files are removed after the sync is complete but I still have only 3 files synced (which I believe is from my three games I played with 0.2.0)

**Comment by majikat768** [comment]
Based on your logs, it looks like v0.2.0 was working correctly... if you click Sync and nothing happens, that just means that the files on your computer and the files in the server are the same- otherwise, it'll either upload files the server doesn't have, or download files your machine doesn't have.  As long as the logger is running, it'll be uploading files to the server automatically, so there's no need to manually sync.

If it helps, on my end it looks like you currently have 12 games logged, so that's how many you should be seeing on your end.

Also, if you have the logger running but you're currently not logged in, it won't upload the files after you click sync.....I plan on fixing this, but for now, one workaround would be to find the folder in the directory 'hsl_files/json/hunterX' and move it into the other folder under hsl_files/json with the really long name.  make sure the directory structure stays the same though ( like 2022/08/05/attributes..... or whatever )

**Comment by MoShU23** [comment]
The problem is that I have 88 games recorded on my computer but none of them were syncing, only the games recorded with 0.2.0 are synced. I moved the .json files into hsl_files/json/*LONG-ID*/2022/08/06/...... and that seems to upload them, it says that I have 107 files synced. I downloaded the program again fresh to see if the files are actually synced and it says that the files are there (all 107) but only two of them gets downloaded, I think it has something to to with the error ( [LOG](https://pastebin.com/ckjitCXv) ) , it seems to get stuck in that _"refreshing token"_ loop forever and none of the details are updated

**Comment by majikat768** [comment]
okay, I think I see what's been happening....I had made some changes in how the json data gets formatted, so it's only the files created with an earlier version which are failing.  So all the files are there, they're just not getting read properly.  Should be a pretty easy fix.
Thanks!!

**Comment by majikat768** [comment]
I've pushed some changes and updated the release, so hopefully it'll be able to sync properly now.
Thanks for your feedback!

**Comment by MoShU23** [comment]
I can confirm that it works, I took 0.2.1 fresh and it synced all the files, all my games shows up in the program. Thanks for the fix.
