### ISSUE TITLE
Feature Idea: Reset KDA

### ISSUE THREAD

**Issue by Skerilyo** [majikat768/HuntStatsLogger#20]
KDA data seems to be calculated from the first launch of the tool and not from the actual player kda, which leaves room for a "Reset" feature.
The idea would be a to add a Reset button which would trigger a popup window asking if we are sure we want to reset our KDA data, and then if yes is pressed, data would be cleaned.
This would "solve" one of the problems that I have with hunt which is after 5000k kills, my kda doesn't really update anymore and I can't get a good idea of were I stand (Yep, it's purely ego driven)

**Comment by majikat768** [comment]
This actually gave me another idea- the KDA here is calculated from all of the recorded games, rather than just be a running value updated after every match, but it'd be pretty easy to add a tool to display the KDA over some period of time- so, your KDA just from hunts in the past week, past month, past year, etc.  Which would allow what you're suggesting, without actually deleting any previous data.
I'll work on that!  Thanks!

**Comment by Skerilyo** [comment]
Closed by 781c335f35a26743c8b3099515a8d78fc5a50113
