### ISSUE TITLE
MMR Prediction

### ISSUE THREAD

**Issue by JSKoenig** [majikat768/HuntStatsLogger#39]
I know its only an estimate but its estimating an MMR increase if you die without any kills.
![000267](https://user-images.githubusercontent.com/41165269/206615116-75015362-314b-43f4-b93e-df90edb9ceb8.png)

**Comment by Huakas** [comment]
yeah the prediction is currently poorly implemented and it annoys the crap out of me.

That's why i put some hours into analysing my MMR changes in HuntStatsLogger and coming up with a way more accurate solution to how Crytek might calculate MMR changes. It's not perfect but at least in all MY games close enough (off by like 2 or 3 mmr at max) and still better than the crap (sorry) this program currently does.

I say 'in MY games' because i figured out this formula by looking at my own games which are around 2800 to 2900 mmr. Meaning if someone is completely out of bounds it could very well still be very wrong.

So here's my suggestion for a better 'predictNextMmr' function that should improve things (@majikat768):

```python
def predictNextMmr(currentMmr = None, currentTs = None):
    if not currentMmr:
        currentMmr = GetCurrentMmr()
    if not currentTs:
        currentTs = GetLastHuntTimestamp()
    predictedChange = 0
    your_kills = execute_query("select downedbyme+killedbyme,mmr from 'hunters' where timestamp is %d and (downedbyme > 0 or killedbyme > 0)" % currentTs)
    your_deaths = execute_query("select downedme+killedme,mmr from 'hunters' where timestamp is %d and (downedme > 0 or killedme > 0)" % currentTs)

    for hunter in your_kills:
        kills = hunter[0]
        mmr = hunter[1]
        mmrValue = min(15, (currentMmr - mmr) / 25)
        predictedChange += (15 - mmrValue) * kills
    for hunter in your_deaths:
        deaths = hunter[0]
        mmr = hunter[1]
        mmrValue = max(-15, (currentMmr - mmr) / 25)
        predictedChange += (-15 - mmrValue) * deaths

    return currentMmr + predictedChange
```

I found that assists are not being used to calculate any MMR changes. So all i am doing here is: for every kill add 15 mmr as a base value (or add -15 mmr for deaths) and then add or reduce that by some calculated value based on mmr difference.

Only problem is that you could lose mmr when killing someone with an mmr difference bigger than 375 which i never had happen so i dont know how Hunt ACTUALLY handles that, maybe you lose mmr for real. But because i doubt that Hunt punishes their players for killing someone much lower than themselves i added a cap with the max() funtion.
Same thing for deaths, we dont want to gain mmr as a 1-star that get's killed by a 6-star, so same cap with min() function.

I hope it's okay for me to just paste this in here, i just want this resolved. And this is as close to the actual mmr function as i could get without having insight into Hunts source code...

**Comment by majikat768** [comment]
Thanks, I appreciate it. It's been on my todo list for a while now, just haven't gotten around to it yet.

**Comment by majikat768** [comment]
Nice work @Huakas, this works much better!  Just pushed an update to the repo with your algorithm, I'll get a build version with it out sometime soon.
