### ISSUE TITLE
Launch Hunt from within the app won't work for me

### ISSUE THREAD

**Issue by MadHoek** [majikat768/HuntStatsLogger#77]
When I click "Launch Hunt" a cmd window opens and closes (so fast I can't see what's happening) after that nothing happens.
If I click it again, after the first time I already clicked, nothing happens at all, not even the cmd window. (or it is too fast for me to see this time)

I don't need this feature but I thought by myself: "if it won't work, why not report it?"

**Comment by majikat768** [comment]
Interesting that there are no errors- one thing you could try, is open a command console in your steam directory, and execute the command:  
`./steam.exe steam://rungameid/594650`

if that works, it could be some kind of permissions error with python, like the app doesn't have access to the steam executable.

**Comment by maxpwr46** [comment]
You changed some things compared to my PR and it now only works if you have Hunt and Steam installed together. If you use a separate library for Hunt (e.g. on a different drive) the current implementation won't work as it cannot find steam.exe relative to hunt.exe.

**Comment by majikat768** [comment]
Ahh that makes sense!
I was having issues launching by itself which is why I added the steam.exe bit.  Thanks!

**Comment by maxpwr46** [comment]
Ok, I wonder what issued you had but generally I like your version to launch it via steam more anyway. I think that's how things are supposed to be done.
I did a bit of research and unfortunately I could not find a way to get steam to tell me the install directory of hunt so I think the best way of solving the issue would be to either

- just prompt the user for the steam dir like you already do for hunt. It surely is not the cleanest solution but in the end I think noone would really care or
- reliably launch the game via the path we already have. The problem you had might be connected to hunt.exe being some kind of launcher while the real game is HuntGame.exe

I would be interested in a solution as well, as I have the game in a different library and still run my own build as it is not working otherwise.

**Comment by majikat768** [comment]
One option would be to check for the existence of steam.exe, and if it's not found, then try just running hunt.exe by itself...I think that'd be easiest, just needs a try/catch block added. Might be nicer to allow the user to set their steam directory, that'll take a little more work though.

**Comment by maxpwr46** [comment]
Well, the former feels like a bandaid fix. It is more robust yes but until we know why running hunt.exe isn't working sometimes, it still won't work for everyone. As there is no time pressure I would prefer the latter as it is guaranteed to work under all circumstances. It is still not a lot of work IMO. I can do it if you want.
